---
title: "Exploring Data and visualization"
author: "Hailey Veirs"
format: html
editor: visual
---

Note: To control what shows up in the html/rendered file in a quarto doc, 
use a "hash-pipe" which is "#| " then warning: false, which makes warnings
disappear, or echo: false, which keeps the code from showing up but outputs 
are still shown. "include: false" makes the code and outputs not included in 
the render.

```{r}
#| warning: false
#| echo: false


library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)

```

## Exploratory Data Viz

Ways to check out and view the data:

```{r}
# Find the column names:
names(penguins)

# Find the dimensions
dim(penguins)

#Show the first 6 lines
head(penguins)

# Last 6 lines
tail(penguins)

```

```{r}
#| include: false 


# skim
skim(penguins)
GGally::ggpairs(penguins)

```

```{r}
#| fig-cap: "Figure 1 Caption"


ggplot(penguins, aes(species, flipper_length_mm)) +
  geom_jitter(width = 0.2, 
              alpha = 0.5, 
              aes(color = species)) + 
  geom_boxplot(fill = NA) +
  theme_light() + 
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) + 
  labs(x = "Penguin Species",
       y = "Flipper Length (mm)", 
       title = "Palmer Archipelago Penguin Flipper Length")
```

```{r}
ggplot(data = penguins, aes(x = bill_depth_mm)) +
  geom_histogram(aes(fill = species), color = "blue") + 
  facet_wrap(~species, ncol = 1)

```


